runtime: go111

handlers:
  # Root page:
  - url: /
    script: auto
    secure: always
    redirect_http_response_code: 301
  # Public files in the root directory:
  - url: /(favicon\.ico|robots\.txt)$
    static_files: \1
    upload: ^(favicon\.ico|robots\.txt)$
    secure: always
    redirect_http_response_code: 301
    expiration: 1h
    http_headers:
      strict-transport-security: max-age=31536000;includeSubDomains;preload
      x-content-type-options: nosniff
